gemini.api.key=AQ.Ab8RN6LNUcBa6RJTRQSOSPhxFFceBl-rkzfHGP-_T8bzabCRRA
gemini.model=gemini-2.5-flash
server.address=0.0.0.0
server.port=8080

String url =
"https://generativelanguage.googleapis.com/v1beta/models/"+ model+ ":generateContent?key="+ apiKey;


